version: '3'

services:
  web:
    build: .
    image: "roommate-finder-image"
    ports:
      - "9000:9000"
    container_name: "roommate-finder-container"
    environment:
      - APP_BASE_URL=http://localhost:9000
      - DATABASE_URL=postgres://ritesh.khore.comp.2020:xT4dzrRqH1sh@ep-rapid-dawn-227431.ap-southeast-1.aws.neon.tech/neondb?connect_timeout=300
      - SHADOW_DATABASE_URL=postgres://ritesh.khore.comp.2020:Fv7IKBcHNE2s@ep-wandering-poetry-832123.ap-southeast-1.aws.neon.tech/neondb?connect_timeout=300
      - NODE_ENV=development
      - SESSION_SECRET=4ea83b16edaa635863ec3be4c35f7820
      - CLOUD_NAME=dmewli5b4
      - CLOUDINARY_API_KEY=826232252792938
      - CLOUDINARY_API_SECRET=GUuGtd2mRKNgOvAgi7ADaq23ZGE
      - HOST=0.0.0.0